# This folder contains no application-specific settings and can be reused as is.
replicaCount: 1
nameOverride: platform-teams-notification-api
appPath: /platform-teams-notification-api
healthUrl: /health
environment: dev
env:
  ASPNETCORE_ENVIRONMENT: "dev"
