name: Shared Application Initialization Workflow

on:
  workflow_call:
    secrets:
      AZURE_TENANT_ID:
        required: true
        description: "Azure Tenant ID"
      AZURE_CLIENT_ID:
        required: true
        description: "Azure Client ID"
      AZURE_SUBSCRIPTION_ID:
        required: true
        description: "Azure Subscription ID"
    inputs:
      environment:
        type: string
        required: true
        description: "Environment"
      SERVICE_PRINCIPAL_NAME:
        type: string
        required: true
        description: "Service Principal Name"
      RESOURCE_GROUP_NAME:
        type: string
        required: true
        description: "Resource Group Name"
      LOG_ANALYTICS_WORKSPACE_ID:
        type: string
        required: true
        description: "Log Analytics Workspace ID"

jobs:
  initialize_workload:
    name: Initialize Workload for ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: run domain powershell
        uses: azure/powershell@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} #required for gh cli to determine "current PR"
          SERVICE_PRINCIPAL_NAME: ${{ vars.SERVICE_PRINCIPAL_NAME }}
          RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
          LOG_ANALYTICS_WORKSPACE_ID: ${{ vars.LOG_ANALYTICS_WORKSPACE_ID }}
        with:
          inlineScript: |
            . ./devops/Initialize-PlatformTeamsNotificationApi.ps1
            Initialize-PlatformTeamsNotificationApi `
              -Environment '${{ inputs.environment }}' `
              -SubscriptionId '${{ secrets.AZURE_SUBSCRIPTION_ID }}' `
              -ServicePrincipalName '${{ inputs.SERVICE_PRINCIPAL_NAME }}' `
              -ResourceGroupName '${{ inputs.RESOURCE_GROUP_NAME }}' `
              -LogAnalyticsWorkspaceId '${{ inputs.LOG_ANALYTICS_WORKSPACE_ID }}'
          azPSVersion: "latest"
          errorActionPreference: "stop"
          failOnStandardError: true
